name: DuelsHub
version: 1.0.0-SNAPSHOT
main: xyz.laur.duels.DuelsHubPlugin
depend: [ProtocolLib]
commands:
  sumo:
    description: Joins a sumo game session
    usage: /sumo <session ID> <randomization factor> <map name> <random teleport>
  games:
    description: Lists all ongoing games
    usage: /games
