name: DuelsHub
version: 1.0.0-SNAPSHOT
main: xyz.laur.duels.DuelsHubPlugin
depend: [ProtocolLib]
commands:
  sumo:
    description: Joins a sumo game session
    usage: /sumo <session ID> <randomization factor> <map name> <random teleport>
  classic:
    description: Joins a classic duels game session
    usage: /classic <session ID> <map name> <random teleport> <spawn distance>
  bridge:
    description: Joins a bridge game session
    usage: /bridge <session ID> <map name>
  games:
    description: Lists all ongoing games
    usage: /games
