name: DuelsHub
version: 1.0.0-SNAPSHOT
main: xyz.laur.duels.DuelsHubPlugin
depend: [ProtocolLib]
commands:
  join:
    description: Joins a game session
    usage: /join <session ID> <randomization factor> <map name>
  games:
    description: Lists all ongoing games
    usage: /games
